In [7]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/customers.csv", sep=";")
df

                                     UUID              Name  Points
0    aa3eaf74-6d9c-4859-b733-5a18a3b2f71b         afonso_rf     792
1    2d3d2dce-d353-4961-ad39-46723efe2100     mariicmartins    1375
2    ca95ef2a-5129-40f4-acbc-2ced25940032           tdlupus     421
3    65662aff-44d6-4f06-b9d9-07445c6e5943            kozat0    4063
4    98b960e7-6b7b-45b7-b7af-60bca40e04b9            gu1z17       0
..                                    ...               ...     ...
786  4a36c617-b018-436a-babc-4374461ab87b         null__var      53
787  403db18e-941e-4e63-ba23-e63c0515876a         lmadriles      50
788  c9bfbbf9-db90-45a7-a72c-4118140038f4  eduardo_cofferri      50
789  4caa2fb3-7ed2-436d-bc35-390feebfdebe          marmschu      50
790  000ff655-fa9f-4baa-a108-47f581ec52a1            cajuuh      52

[791 rows x 3 columns]

In [3]:
df["Points_double"] = df["Points"] * 2
df

,UUID,Name,Points,Points_double
0,aa3eaf74-6d9c-4859-b733-5a18a3b2f71b,afonso_rf,792,1584
1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,2750
2,ca95ef2a-5129-40f4-acbc-2ced25940032,tdlupus,421,842
3,65662aff-44d6-4f06-b9d9-07445c6e5943,kozat0,4063,8126
4,98b960e7-6b7b-45b7-b7af-60bca40e04b9,gu1z17,0,0
...,...,...,...,...
786,4a36c617-b018-436a-babc-4374461ab87b,null__var,53,106
787,403db18e-941e-4e63-ba23-e63c0515876a,lmadriles,50,100
788,c9bfbbf9-db90-45a7-a72c-4118140038f4,eduardo_cofferri,50,100
789,4caa2fb3-7ed2-436d-bc35-390feebfdebe,marmschu,50,100
790,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,52,104

In [5]:
df["Points_ratio"] = df["Points_double"] / df["Points"]
df

,UUID,Name,Points,Points_double,Points_ratio
0,aa3eaf74-6d9c-4859-b733-5a18a3b2f71b,afonso_rf,792,1584,2.0
1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,2750,2.0
2,ca95ef2a-5129-40f4-acbc-2ced25940032,tdlupus,421,842,2.0
3,65662aff-44d6-4f06-b9d9-07445c6e5943,kozat0,4063,8126,2.0
4,98b960e7-6b7b-45b7-b7af-60bca40e04b9,gu1z17,0,0,NaN
...,...,...,...,...,...
786,4a36c617-b018-436a-babc-4374461ab87b,null__var,53,106,2.0
787,403db18e-941e-4e63-ba23-e63c0515876a,lmadriles,50,100,2.0
788,c9bfbbf9-db90-45a7-a72c-4118140038f4,eduardo_cofferri,50,100,2.0
789,4caa2fb3-7ed2-436d-bc35-390feebfdebe,marmschu,50,100,2.0
790,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,52,104,2.0

In [6]:
df["Constante"] = 1
df

,UUID,Name,Points,Points_double,Points_ratio,Constante
0,aa3eaf74-6d9c-4859-b733-5a18a3b2f71b,afonso_rf,792,1584,2.0,1
1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,2750,2.0,1
2,ca95ef2a-5129-40f4-acbc-2ced25940032,tdlupus,421,842,2.0,1
3,65662aff-44d6-4f06-b9d9-07445c6e5943,kozat0,4063,8126,2.0,1
4,98b960e7-6b7b-45b7-b7af-60bca40e04b9,gu1z17,0,0,NaN,1
...,...,...,...,...,...,...
786,4a36c617-b018-436a-babc-4374461ab87b,null__var,53,106,2.0,1
787,403db18e-941e-4e63-ba23-e63c0515876a,lmadriles,50,100,2.0,1
788,c9bfbbf9-db90-45a7-a72c-4118140038f4,eduardo_cofferri,50,100,2.0,1
789,4caa2fb3-7ed2-436d-bc35-390feebfdebe,marmschu,50,100,2.0,1
790,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,52,104,2.0,1

In [8]:
df["Points_log"] = np.log(df["Points"])
df

c:\Users\Joaoc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

,UUID,Name,Points,Points_double,Points_ratio,Constante,Points_log
0,aa3eaf74-6d9c-4859-b733-5a18a3b2f71b,afonso_rf,792,1584,2.0,1,6.674561
1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,2750,2.0,1,7.226209
2,ca95ef2a-5129-40f4-acbc-2ced25940032,tdlupus,421,842,2.0,1,6.042633
3,65662aff-44d6-4f06-b9d9-07445c6e5943,kozat0,4063,8126,2.0,1,8.309677
4,98b960e7-6b7b-45b7-b7af-60bca40e04b9,gu1z17,0,0,NaN,1,-inf
...,...,...,...,...,...,...,...
786,4a36c617-b018-436a-babc-4374461ab87b,null__var,53,106,2.0,1,3.970292
787,403db18e-941e-4e63-ba23-e63c0515876a,lmadriles,50,100,2.0,1,3.912023
788,c9bfbbf9-db90-45a7-a72c-4118140038f4,eduardo_cofferri,50,100,2.0,1,3.912023
789,4caa2fb3-7ed2-436d-bc35-390feebfdebe,marmschu,50,100,2.0,1,3.912023
790,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,52,104,2.0,1,3.951244

In [9]:
df["Name"].str.upper()

0             AFONSO_RF
1         MARIICMARTINS
2               TDLUPUS
3                KOZAT0
4                GU1Z17
             ...
786           NULL__VAR
787           LMADRILES
788    EDUARDO_COFFERRI
789            MARMSCHU
790              CAJUUH
Name: Name, Length: 791, dtype: object

In [13]:
def get_first(nome: str):
    nome = nome.upper()
    return nome.split("_")[0]

In [14]:
get_first("Joao_Pedro")

'JOAO'

In [15]:
df["Name_first"] = df["Name"].apply(get_first)
df

,UUID,Name,Points,Points_double,Points_ratio,Constante,Points_log,Name_first
0,aa3eaf74-6d9c-4859-b733-5a18a3b2f71b,afonso_rf,792,1584,2.0,1,6.674561,AFONSO
1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,2750,2.0,1,7.226209,MARIICMARTINS
2,ca95ef2a-5129-40f4-acbc-2ced25940032,tdlupus,421,842,2.0,1,6.042633,TDLUPUS
3,65662aff-44d6-4f06-b9d9-07445c6e5943,kozat0,4063,8126,2.0,1,8.309677,KOZAT0
4,98b960e7-6b7b-45b7-b7af-60bca40e04b9,gu1z17,0,0,NaN,1,-inf,GU1Z17
...,...,...,...,...,...,...,...,...
786,4a36c617-b018-436a-babc-4374461ab87b,null__var,53,106,2.0,1,3.970292,NULL
787,403db18e-941e-4e63-ba23-e63c0515876a,lmadriles,50,100,2.0,1,3.912023,LMADRILES
788,c9bfbbf9-db90-45a7-a72c-4118140038f4,eduardo_cofferri,50,100,2.0,1,3.912023,EDUARDO
789,4caa2fb3-7ed2-436d-bc35-390feebfdebe,marmschu,50,100,2.0,1,3.912023,MARMSCHU
790,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,52,104,2.0,1,3.951244,CAJUUH

In [16]:
df["Name"].apply(lambda x: x.upper().split("_")[0])

0             AFONSO
1      MARIICMARTINS
2            TDLUPUS
3             KOZAT0
4             GU1Z17
           ...
786             NULL
787        LMADRILES
788          EDUARDO
789         MARMSCHU
790           CAJUUH
Name: Name, Length: 791, dtype: object

In [18]:
def intervalo_pontos(pontos):
    if pontos < 2500:
        return "baixo"
    elif pontos < 1500:
        return "medio"
    else: 
        return "alto"
    
df["Faixa_pontos"] = df["Points"].apply(intervalo_pontos)
df

,UUID,Name,Points,Points_double,Points_ratio,Constante,Points_log,Name_first,Faixa_pontos
0,aa3eaf74-6d9c-4859-b733-5a18a3b2f71b,afonso_rf,792,1584,2.0,1,6.674561,AFONSO,baixo
1,2d3d2dce-d353-4961-ad39-46723efe2100,mariicmartins,1375,2750,2.0,1,7.226209,MARIICMARTINS,baixo
2,ca95ef2a-5129-40f4-acbc-2ced25940032,tdlupus,421,842,2.0,1,6.042633,TDLUPUS,baixo
3,65662aff-44d6-4f06-b9d9-07445c6e5943,kozat0,4063,8126,2.0,1,8.309677,KOZAT0,alto
4,98b960e7-6b7b-45b7-b7af-60bca40e04b9,gu1z17,0,0,NaN,1,-inf,GU1Z17,baixo
...,...,...,...,...,...,...,...,...,...
786,4a36c617-b018-436a-babc-4374461ab87b,null__var,53,106,2.0,1,3.970292,NULL,baixo
787,403db18e-941e-4e63-ba23-e63c0515876a,lmadriles,50,100,2.0,1,3.912023,LMADRILES,baixo
788,c9bfbbf9-db90-45a7-a72c-4118140038f4,eduardo_cofferri,50,100,2.0,1,3.912023,EDUARDO,baixo
789,4caa2fb3-7ed2-436d-bc35-390feebfdebe,marmschu,50,100,2.0,1,3.912023,MARMSCHU,baixo
790,000ff655-fa9f-4baa-a108-47f581ec52a1,cajuuh,52,104,2.0,1,3.951244,CAJUUH,baixo

In [22]:
df["UUID"].apply(lambda x: x[-3:])

0      71b
1      100
2      032
3      943
4      4b9
      ...
786    87b
787    76a
788    8f4
789    ebe
790    2a1
Name: UUID, Length: 791, dtype: object

In [24]:
data = {
    "nome": ["Teo", "Nah", "Maria", "Lara"],
    "recencia": [1,30,10,45],
    "valor":[100,2000, 15, 500],
    "frequencia":[2, 5, 1, 15]
}

df_crm = pd.DataFrame(data)
df_crm

    nome  recencia  valor  frequencia
0    Teo         1    100           2
1    Nah        30   2000           5
2  Maria        10     15           1
3   Lara        45    500          15

In [25]:
def rfv(row):
    
    nota = 0
    
    if row['recencia'] <= 10:
        nota += 10
    elif 10 < row['recencia'] <= 30:
        nota += 5
    elif row['recencia'] > 30:
        nota += 0

    if row['valor'] > 1000:
        nota += 10
    elif 100 <= row['valor'] < 1000:
        nota += 5
    elif row['valor'] < 100:
        nota += 0

    if row['frequencia'] > 10:
        nota += 10
    elif 5 <= row['frequencia'] < 10:
        nota += 5
    elif row['frequencia'] < 5:
        nota += 0
    
    return nota

In [26]:
df_crm["RFV"] = df_crm.apply(rfv, axis=1)
df_crm

    nome  recencia  valor  frequencia  RFV
0    Teo         1    100           2   15
1    Nah        30   2000           5   20
2  Maria        10     15           1   10
3   Lara        45    500          15   15

In [27]:

df_crm.iloc[0]

nome          Teo
recencia        1
valor         100
frequencia      2
RFV            15
Name: 0, dtype: object