In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("../data/products.csv", 
                sep=";",
                names=["Id", "Name", "Description"])
df

,Id,Name,Description
0,1,ChatMessage,Mensagem do chat da Twitch
1,2,Resgatar Ponei,Poneis resgatados a partir dos pontos que a Tw...
2,3,Lista de presença,Assinatura da lista durante as lives (!presente)
3,4,Troca de Pontos StreamElements,Troca de cubos por datapoints
4,5,Presença Streak,Streak de pontos para quem tem recorrência de ...

In [6]:
df.rename(columns={"Name": "Nome", 
                  "Description": "Descrição"}, 
                  inplace=True)
df

,Id,Nome,Descrição
0,1,ChatMessage,Mensagem do chat da Twitch
1,2,Resgatar Ponei,Poneis resgatados a partir dos pontos que a Tw...
2,3,Lista de presença,Assinatura da lista durante as lives (!presente)
3,4,Troca de Pontos StreamElements,Troca de cubos por datapoints
4,5,Presença Streak,Streak de pontos para quem tem recorrência de ...