In [1]:
import pandas as pd

In [10]:
data = {
  "nome": ["teo", "maria", "lara", "nah"],
  "sobrenome": ["calvo", "ataide", "calvo", "calvo"],
  "idade": [31, 32, 31, 2]
}

In [11]:
data["idade"][0]

31

In [12]:
df = pd.DataFrame(data)
df

    nome sobrenome  idade
0    teo     calvo     31
1  maria    ataide     32
2   lara     calvo     31
3    nah     calvo      2

In [14]:
df["idade"][0]

np.int64(31)

In [15]:
df["idade"].iloc[0]

np.int64(31)

In [16]:
type(df["idade"])

pandas.core.series.Series

In [17]:
df.iloc[0]

nome           teo
sobrenome    calvo
idade           31
Name: 0, dtype: object

In [18]:
type(df.iloc[0])

pandas.core.series.Series

In [19]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [20]:
df.columns

Index(['nome', 'sobrenome', 'idade'], dtype='object')

In [23]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   nome       4 non-null      object
 1   sobrenome  4 non-null      object
 2   idade      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 592.0 bytes

In [24]:
df.dtypes

nome         object
sobrenome    object
idade         int64
dtype: object

In [26]:
df["peso"] = [80, 53, 65, 14]

In [29]:
sumario = df.describe()

In [30]:
sumario["peso"]["mean"]

np.float64(53.0)

In [32]:
df.head(2)

    nome sobrenome  idade  peso
0    teo     calvo     31    80
1  maria    ataide     32    53

In [33]:
df.tail(2)

   nome sobrenome  idade  peso
2  lara     calvo     31    65
3   nah     calvo      2    14